swagger: '2.0'
info:
  description: |
    Some description should be here
  version: 1.0.0
  title: Swagger Color
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
# host: petstore.swagger.io
# basePath: /v2
tags:
- name: color
  description: Everything about your Pets
  externalDocs:
    description: Find out more
    url: http://swagger.io

# schemes:
# - http
paths:
  /color/{colorId}:
    get:
      tags:
      - color
      summary: Find color by ID
      description: Returns a single color
      operationId: getColorById
      produces:
      - application/json
      parameters:
      - name: colorId
        in: path
        description: ID of color to return
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Color'
        400:
          description: Invalid ID supplied
        404:
          description: Pet not found


definitions:
  Color:
    type: object
    properties:
      id:
        type: integer
        format: int64
      petId:
        type: integer
        format: int64
      quantity:
        type: integer
        format: int32
      shipDate:
        type: string
        format: date-time
      status:
        type: string
        description: Order Status
        enum:
        - placed
        - approved
        - delivered
      complete:
        type: boolean
        default: false
basePath: /slowikps/color/1.0.0
schemes:
 - https
 - http